template_path: templates/ddb-dev-url.yaml
dependencies:
hooks:
  before_create:
    - !cmd "echo creating..."
  after_create:
    - !cmd "echo created"
    - !cmd "echo done"
  after_update:
parameters:
  InvTableName: urls
stack_tags:
  app: turl
  bu: pi
  env: dev
  pool: db
